[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "backend-comparison",
    "crates/*",
    "crates/burn-import/pytorch-tests",
    "crates/burn-import/onnx-tests",
    "examples/*",
    "examples/pytorch-import/model",
    "xtask",
]

exclude = [
    "examples/notebook",
    "examples/raspberry-pi-pico", # will cause dependency building issues otherwise
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
version = "0.17.0"

[workspace.dependencies]
atomic_float = "1"
bytemuck = "1.21.0"
candle-core = { version = "0.8.4" }
clap = { version = "4.5.27", features = ["derive"] }
colored = "2.1.0"
console_error_panic_hook = "0.1.7"
csv = "1.3.1"
dashmap = "6.1.0"
data-encoding = { version = "2.8.0", default-features = false, features = [
    "alloc",
] }
dirs = "5.0.1"
fake = "3.0.1"
flate2 = "1.1.0"
float-cmp = "0.10.0"
getrandom = { version = "0.3.1", default-features = false }
gix-tempfile = { version = "15.0.0", features = ["signals"] }
globwalk = "0.9.1"
hashbrown = "0.15.2"
hound = "3.5.1"
image = "0.25.5"
indicatif = "0.17.11"
js-sys = "0.3.72"
libm = "0.2.11"
log = { default-features = false, version = "0.4.25" }
md5 = "0.7.0"
paste = "1"
percent-encoding = "2.3.1"
polars = { version = "0.46.0", features = ["lazy"] }
pretty_assertions = "1.4.1"
proc-macro2 = "1.0.94"
protobuf = "3.7.2"
protobuf-codegen = "3.7.1"
quote = "1.0.39"
r2d2 = "0.8.10"
r2d2_sqlite = "0.25.0"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.12", default-features = false, features = [
    "rustls-tls",
] }
rmp-serde = "1.3.0"
rstest = "0.23.0"
rusqlite = "0.32.1"
rust-format = "0.3.4"
sanitize-filename = "0.6.0"
serde_bytes = { version = "0.11.17", default-features = false, features = [
    "alloc",
] } # alloc for no_std
serde_rusqlite = "0.36.0"
serial_test = "3.2.0"
spin = { version = "0.9.8", features = [
    "mutex",
    "spin_mutex",
    "portable-atomic",
] }
strum = "0.26.3"
strum_macros = "0.26.4"
syn = { version = "2.0.100", features = ["full", "extra-traits"] }
tempfile = "3.17.1"
thiserror = "2.0.11"
tokio = { version = "1.42.0", features = ["rt", "macros"] }
tracing-appender = "0.2.3"
tracing-core = "0.1.33"
tracing-subscriber = "0.3.19"
web-time = "1.1.0"
zip = "2.3.0"

# Async handling
async-channel = "2.3"
futures-lite = { version = "2.5.0", default-features = false }

# Terminal UI
ratatui = "0.29.0"

# WGPU stuff
text_placeholder = "0.5.1"
wgpu = "24.0.1"

# Benchmarks and Burnbench
arboard = "3.4.1"
chrono = "0.4.39"
os_info = "3.10.0"
wsl = "0.1.0"

# TODO: update to official 2.0 release once MSRV is bumped to 1.85
bincode = { version = "=2.0.0-rc.3", features = [
    "alloc",
    "serde",
], default-features = false }

#
# The following packages disable the "std" feature for no_std compatibility
#
cfg-if = "1.0.0"
derive-new = { version = "0.7.0", default-features = false }

blas-src = { version = "0.10.0", default-features = false }
bon = "3.5.0"
half = { version = "2.5.0", features = [
    "alloc",
    "num-traits",
    "serde",
], default-features = false }
macerator = { version = "0.2.6" }
matrixmultiply = { version = "0.3.9", default-features = false }
ndarray = { version = "0.16.1", default-features = false }
num-traits = { version = "0.2.19", default-features = false, features = [
    "libm",
] } # libm is for no_std
openblas-src = "0.10.11"
rand = { version = "0.9.0", default-features = false, features = [
    "std_rng",
] } # std_rng is for no_std
rand_distr = { version = "0.5.0", default-features = false }
serde = { version = "1.0.218", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
serde_json = { version = "1.0.140", default-features = false }
uuid = { version = "1.16.0", default-features = false }

libc = "0.2.170"
nvml-wrapper = "0.10.0"
sysinfo = "0.33.1"
systemstat = "0.2.3"
tch = "0.19.0"
torch-sys = "0.19.0"    # matches what tch is using, required for lib detection

ahash = { version = "0.8.11", default-features = false }
portable-atomic = { version = "1.11.0" }
portable-atomic-util = { version = "0.2.4", features = ["alloc"] }

### For the main burn branch. ###
cubecl = { git = "https://github.com/zlogic/cubecl", default-features = false, rev = "e5d21c02e36e5580375544cf149e58af5b1631ad" }
cubecl-common = { git = "https://github.com/zlogic/cubecl", default-features = false, rev = "e5d21c02e36e5580375544cf149e58af5b1631ad" }
cubecl-std = { git = "https://github.com/zlogic/cubecl", default-features = false, rev = "e5d21c02e36e5580375544cf149e58af5b1631ad" }
### For local development. ###
# cubecl = { path = "../cubecl/crates/cubecl", default-features = false }
# cubecl-common = { path = "../cubecl/crates/cubecl-common", default-features = false }
# cubecl-std = { path = "../cubecl/crates/cubecl-std", default-features = false }
### For the release. ###
# cubecl = { version = "0.4.0", default-features = false }
# cubecl-common = { version = "0.4.0", default-features = false }
# cubecl-std = { version = "0.4.0", default-features = false }

### For xtask crate ###
tracel-xtask = { version = "=1.1.9" }

[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
